-- MySQL Script generated by MySQL Workbench
-- Fri Dec  9 18:47:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authors` (
  `AuthorID` INT NOT NULL AUTO_INCREMENT,
  `F` VARCHAR(45) NOT NULL,
  `I` VARCHAR(45) NOT NULL,
  `O` VARCHAR(45) NOT NULL,
  `Date_Birth` VARCHAR(45) NOT NULL,
  `Date_Death` VARCHAR(45) NOT NULL,
  `Comment` VARCHAR(45) NULL,
  PRIMARY KEY (`AuthorID`),
  UNIQUE INDEX `AuthorID_UNIQUE` (`AuthorID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conditions` (
  `ConditionID` INT NOT NULL AUTO_INCREMENT,
  `Condition_Name` VARCHAR(45) NULL,
  `Comment` VARCHAR(100) NULL,
  PRIMARY KEY (`ConditionID`),
  UNIQUE INDEX `ConditionID_UNIQUE` (`ConditionID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `BookID` INT NOT NULL AUTO_INCREMENT,
  `Book` VARCHAR(45) NULL,
  `Publisher` VARCHAR(45) NULL,
  `Publication_Date` VARCHAR(45) NULL,
  `Edition` VARCHAR(45) NULL,
  `Cost` VARCHAR(45) NULL,
  `SRPrice` VARCHAR(45) NULL,
  `ConditionID` INT NULL,
  `Book_Status` VARCHAR(45) NULL,
  PRIMARY KEY (`BookID`),
  UNIQUE INDEX `BookID_UNIQUE` (`BookID` ASC) VISIBLE,
  INDEX `Conditions_idx` (`ConditionID` ASC) VISIBLE,
  CONSTRAINT `Conditions`
    FOREIGN KEY (`ConditionID`)
    REFERENCES `mydb`.`Conditions` (`ConditionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buyers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buyers` (
  `BuyerID` INT NOT NULL,
  `F` VARCHAR(45) NOT NULL,
  `I` VARCHAR(45) NOT NULL,
  `O` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BuyerID`),
  UNIQUE INDEX `BuyerID_UNIQUE` (`BuyerID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workers` (
  `WorkerID` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `F` VARCHAR(45) NOT NULL,
  `I` VARCHAR(45) NOT NULL,
  `O` VARCHAR(45) NOT NULL,
  `Work_Position` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `WorkerID_UNIQUE` (`WorkerID` ASC) VISIBLE,
  PRIMARY KEY (`WorkerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment_Methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment_Methods` (
  `Payment_MethodID` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `Payment_Method_Name` VARCHAR(45) NULL,
  `Comment` VARCHAR(100) NULL,
  `Current_Usage` TINYINT ZEROFILL NOT NULL DEFAULT 1,
  PRIMARY KEY (`Payment_MethodID`),
  UNIQUE INDEX `idPayment_Methods_UNIQUE` (`Payment_MethodID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Purchases` (
  `SaleID` INT NOT NULL AUTO_INCREMENT,
  `BookID` INT NOT NULL,
  `BuyerID` INT ZEROFILL NOT NULL,
  `WorkerID` INT NOT NULL,
  `Order_Date` VARCHAR(45) NOT NULL,
  `Devilery_Date` VARCHAR(45) NOT NULL,
  `Payment_MethodID` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`SaleID`),
  INDEX `Worker_idx` (`WorkerID` ASC) VISIBLE,
  INDEX `Purchases_Byuer_idx` (`BuyerID` ASC) VISIBLE,
  INDEX `Purchases_Payment_Method_idx` (`Payment_MethodID` ASC) VISIBLE,
  CONSTRAINT `Purchases_Worker`
    FOREIGN KEY (`WorkerID`)
    REFERENCES `mydb`.`Workers` (`WorkerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Purchases_Byuer`
    FOREIGN KEY (`BuyerID`)
    REFERENCES `mydb`.`Buyers` (`BuyerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Purchases_Payment_Method`
    FOREIGN KEY (`Payment_MethodID`)
    REFERENCES `mydb`.`Payment_Methods` (`Payment_MethodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authors_Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authors_Books` (
  `AuthorID` INT NOT NULL,
  `BookID` INT NOT NULL,
  UNIQUE INDEX `AuthorID_UNIQUE` (`AuthorID` ASC) VISIBLE,
  INDEX `Books_idx` (`BookID` ASC) VISIBLE,
  PRIMARY KEY (`AuthorID`, `BookID`),
  CONSTRAINT `Authors`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `mydb`.`Authors` (`AuthorID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Books`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Books` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchase_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Purchase_Details` (
  `SaleID` INT NOT NULL,
  `BookID` INT NOT NULL,
  `Sale_Price` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`SaleID`, `BookID`),
  INDEX `Purchase_BookID_idx` (`BookID` ASC) VISIBLE,
  CONSTRAINT `Purchase_BookID`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Books` (`BookID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Purchase_SaleID`
    FOREIGN KEY (`SaleID`)
    REFERENCES `mydb`.`Purchases` (`SaleID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
